# Generated by Django 3.1.4 on 2021-06-06 18:36

import _socket
from django.db import migrations, models
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuralCommunityRapidAssessment',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('subject_identifier_as_pk', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_identifier_aka', models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('community', models.CharField(max_length=200, null=True, verbose_name='Community')),
                ('plot_number', models.CharField(max_length=100, null=True, verbose_name='Plot Number')),
                ('district', models.CharField(max_length=200, null=True, verbose_name='District')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='Full name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('age_in_years', models.IntegerField(help_text='(Years)', verbose_name='What is the participants age?')),
                ('contracts', models.CharField(max_length=100, null=True, verbose_name='Contacts')),
                ('role', models.CharField(choices=[('kgosi', 'Kgosi'), ('kgosana', 'Kgosana'), ('mp', 'Member of Parliament'), ('councillor', 'Councillor'), ('pastor', 'Pastor/Priest/Imam/Rabbi'), ('commitee_member', 'Member of Committee in the Village'), ('public_servant', 'Public Servant'), ('community_member', 'Community Member'), ('other', 'Other')], max_length=200, null=True, verbose_name='What is your current role?')),
                ('role_other', models.CharField(max_length=200, null=True, verbose_name='If the answer to role above is other specify')),
                ('covid19_awareness', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=10, null=True, verbose_name='Are you aware of Coronavirus/COVID-19 Vaccine?')),
                ('covid19_learning', models.CharField(choices=[('tv', 'TV'), ('radio', 'Radio'), ('social_media', 'Social media (Facebook, Twitter, Instagram, WhatsApp)'), ('print_media', 'Print media (news papers)'), ('people', 'People'), ('health_worker', 'Health Worker'), ('redcross_volunteers', 'Botswana Red Cross Volunteers'), ('other', 'Other')], max_length=100, null=True, verbose_name='If yes, where did you learn about Coronavirus/COVID-19 Vaccine?')),
                ('covid19_learning_other', models.CharField(max_length=200, null=True, verbose_name='If the answer to where you learnt about COVID-19 above is other specify')),
                ('vaccine_assess', models.CharField(choices=[('not_easy', 'Not easy'), ('moderately_easy', 'Moderately easy'), ('extremely_easy', 'Extremely easy')], max_length=100, null=True, verbose_name='How easy is it to get vaccination service for yourself?')),
                ('vaccine_assess_reason', models.CharField(max_length=200, null=True, verbose_name='If not easy what are the reasons?')),
                ('vaccine_assess_challanges', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=100, null=True, verbose_name='Is there anything that may stop you from getting the COVID-19 vaccine injection?')),
                ('va_challanges_other', models.CharField(max_length=200, null=True, verbose_name='If the answer to things that may stop you from getting the vaccine is yes specify reasons')),
                ('vaccine_trust', models.CharField(choices=[('not_at_all', 'Not at all'), ('moderately', 'Moderately'), ('very_much', 'Very much')], max_length=100, null=True, verbose_name='How much would you trust the new COVID-19 vaccine if it was available for you?')),
                ('vaccine_trust_other', models.CharField(max_length=200, null=True, verbose_name='If you do not trust the vaccine state reasons why')),
                ('vaccine_recommendation', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('not_sure', 'Not sure')], max_length=100, null=True, verbose_name='If the new COVID-19 vaccine is recommended for you, would you take it?')),
                ('vaccine_recommendation_other', models.CharField(max_length=200, null=True, verbose_name='If you No or Not sure, why')),
                ('vaccination_importance', models.CharField(choices=[('very_important', 'Very Important'), ('important', 'Important'), ('not_important', 'Not important'), ('not_important_at_all', 'Not important at all')], max_length=100, null=True, verbose_name='How important is it to get vaccine?')),
                ('vaccine_reco_others', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('not_sure', 'Not sure')], max_length=100, null=True, verbose_name='Would you recommend COVID-19 vaccine to your community followers?')),
                ('vaccine_recom_other', models.CharField(max_length=200, null=True, verbose_name='If you No or Not sure, why')),
                ('vaccine_reco_someone', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=100, null=True, verbose_name='Would you recommend the COVID-19 vaccine to someone?')),
                ('vaccine_reco_someone_other', models.CharField(max_length=200, null=True, verbose_name='If No give reasons')),
            ],
            options={
                'verbose_name': 'Rural Community Rapid Assessment',
                'verbose_name_plural': 'Rural Community Rapid Assessment',
            },
        ),
    ]
