# Generated by Django 3.1.4 on 2021-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_recom_other',
            field=models.CharField(max_length=200, null=True, verbose_name='If you No or Not sure, why'),
        ),
    ]
