# Generated by Django 3.1.4 on 2021-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='age_in_years',
            field=models.IntegerField(blank=True, help_text='(Years)', null=True, verbose_name='What is the participants age?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='community',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='contracts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='covid19_awareness',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=10, null=True, verbose_name='Are you aware of Coronavirus/COVID-19 Vaccine?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='covid19_learning',
            field=models.CharField(blank=True, choices=[('tv', 'TV'), ('radio', 'Radio'), ('social_media', 'Social media (Facebook, Twitter, Instagram, WhatsApp)'), ('print_media', 'Print media (news papers)'), ('people', 'People'), ('health_worker', 'Health Worker'), ('redcross_volunteers', 'Botswana Red Cross Volunteers'), ('other', 'Other')], max_length=100, null=True, verbose_name='If yes, where did you learn about Coronavirus/COVID-19 Vaccine?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='covid19_learning_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If the answer to where you learnt about COVID-19 above is other specify'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='plot_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plot Number'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='role',
            field=models.CharField(blank=True, choices=[('kgosi', 'Kgosi'), ('kgosana', 'Kgosana'), ('mp', 'Member of Parliament'), ('councillor', 'Councillor'), ('pastor', 'Pastor/Priest/Imam/Rabbi'), ('commitee_member', 'Member of Committee in the Village'), ('public_servant', 'Public Servant'), ('community_member', 'Community Member'), ('other', 'Other')], max_length=200, null=True, verbose_name='What is your current role?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='role_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If the answer to role above is other specify'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='va_challanges_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If the answer to things that may stop you from getting the vaccine is yes specify reasons'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccination_importance',
            field=models.CharField(blank=True, choices=[('very_important', 'Very Important'), ('important', 'Important'), ('not_important', 'Not important'), ('not_important_at_all', 'Not important at all')], max_length=100, null=True, verbose_name='How important is it to get vaccine?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_assess',
            field=models.CharField(blank=True, choices=[('not_easy', 'Not easy'), ('moderately_easy', 'Moderately easy'), ('extremely_easy', 'Extremely easy')], max_length=100, null=True, verbose_name='How easy is it to get vaccination service for yourself?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_assess_challanges',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=100, null=True, verbose_name='Is there anything that may stop you from getting the COVID-19 vaccine injection?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_assess_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If not easy what are the reasons?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_reco_others',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('not_sure', 'Not sure')], max_length=100, null=True, verbose_name='Would you recommend COVID-19 vaccine to your community followers?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_reco_someone',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=100, null=True, verbose_name='Would you recommend the COVID-19 vaccine to someone?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_reco_someone_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If No give reasons'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_recom_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If you No or Not sure, why'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_recommendation',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('not_sure', 'Not sure')], max_length=100, null=True, verbose_name='If the new COVID-19 vaccine is recommended for you, would you take it?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_recommendation_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If you No or Not sure, why'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_trust',
            field=models.CharField(blank=True, choices=[('not_at_all', 'Not at all'), ('moderately', 'Moderately'), ('very_much', 'Very much')], max_length=100, null=True, verbose_name='How much would you trust the new COVID-19 vaccine if it was available for you?'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='vaccine_trust_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If you do not trust the vaccine state reasons why'),
        ),
    ]
