# Generated by Django 3.1.4 on 2021-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210606_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='subject_identifier',
            field=models.CharField(max_length=50, null=True, verbose_name='Subject Identifier'),
        ),
    ]
