# Generated by Django 3.1.4 on 2021-06-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('analysis', '0003_auto_20210606_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruralcommunityrapidassessment',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
