# Generated by Django 3.1.4 on 2021-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_ruralcommunityrapidassessment_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Report Date'),
        ),
    ]
