# Generated by Django 3.1.4 on 2021-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210606_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='community',
            field=models.CharField(blank=True, choices=[('malwelwe_kweneng', 'Malwelwe, Kweneng District'), ('komana_north_west', 'Komana, North West District'), ('nxaraga_ngamiland', 'Nxaraga, Ngamiland District'), ('werda_kgalagadi_south', 'Werda, Kgalagadi South District'), ('maun_ngamiland', 'Maun, Ngamiland District'), ('shakawe_north_west', 'Shakawe, North West District'), ('kang_kgalagadi_north', 'Kang, Kgalagadi North District'), ('bokspits_kgalagadi', 'Bokspits, Kgalagadi District'), ('tsetseng_kweneng', 'Tsetseng, Kweneng District'), ('gakhibana_kgalagadi_south', 'Gakhibana, Kgalagadi South District'), ('maubelo_kgalagadi_south', 'Maubelo, Kgalagadi South District'), ('kokotsha_kgalagadi_south', 'Kokotsha, Kgalagadi South District'), ('tsabong_kgalagadi_south', 'Tsabong, Kgalagadi South District'), ('etsha_6_ngamiland_west', 'Etsha 6, Ngamiland West District'), ('tsau_north_west', 'Tsau, North West District')], max_length=200, null=True, verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='ruralcommunityrapidassessment',
            name='district',
            field=models.CharField(blank=True, choices=[('kweneng', 'Kweneng District'), ('kgalagadi_south', 'Kgalagadi South District'), ('kgalagadi_north', 'Kgalagadi North District'), ('kgalagadi', 'Kgalagadi District'), ('ngamiland', 'Ngamiland District'), ('north_west', 'North West District'), ('ngamiland_west', 'Ngamiland West District')], max_length=200, null=True, verbose_name='District'),
        ),
    ]
