# Generated by Django 3.1.4 on 2021-07-03 15:09

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('analysis', '0008_auto_20210703_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('subject_identifier_as_pk', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_identifier_aka', models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a')),
                ('subject_identifier', models.CharField(max_length=50, null=True, verbose_name='Subject Identifier')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='Report Date')),
                ('district', models.CharField(blank=True, choices=[('kweneng', 'Kweneng District'), ('kgalagadi_south', 'Kgalagadi South District'), ('kgalagadi_north', 'Kgalagadi North District'), ('kgalagadi', 'Kgalagadi District'), ('ngamiland', 'Ngamiland District'), ('north_west', 'North West District'), ('ngamiland_west', 'Ngamiland West District'), ('ghanzi', 'Ghanzi District'), ('kweneng', 'Kweneng District')], max_length=200, null=True, verbose_name='District')),
                ('village', models.CharField(blank=True, choices=[('malwelwe_kweneng', 'Malwelwe, Kweneng District'), ('komana_north_west', 'Komana, North West District'), ('nxaraga_ngamiland', 'Nxaraga, Ngamiland District'), ('werda_kgalagadi_south', 'Werda, Kgalagadi South District'), ('maun_ngamiland', 'Maun, Ngamiland District'), ('shakawe_north_west', 'Shakawe, North West District'), ('kang_kgalagadi_north', 'Kang, Kgalagadi North District'), ('bokspits_kgalagadi', 'Bokspits, Kgalagadi District'), ('tsetseng_kweneng', 'Tsetseng, Kweneng District'), ('gakhibana_kgalagadi_south', 'Gakhibana, Kgalagadi South District'), ('maubelo_kgalagadi_south', 'Maubelo, Kgalagadi South District'), ('kokotsha_kgalagadi_south', 'Kokotsha, Kgalagadi South District'), ('tsabong_kgalagadi_south', 'Tsabong, Kgalagadi South District'), ('etsha_6_ngamiland_west', 'Etsha 6, Ngamiland West District'), ('tsau_north_west', 'Tsau, North West District'), ('kuke_ghanzi', 'Kuke, Ghanzi'), ('inalegolo_kgalagadi_north', 'Inalegolo, Kgalagadi north'), ('lehututu_kgalagadi_north', 'Lehututu, Kgalagadi north'), ('hukuntsi_kgalagadi_north', 'Hukuntsi, Kgalagadi north'), ('tshane_kgalagadi_north', 'Tshane, Kgalagadi north'), ('diphuduhudu_kweneng', 'Diphuduhudu, Kweneng'), ('sorilatholo_kweneng', 'Sorilatholo, Kweneng'), ('tshwaane_kweneng', 'Tshwaane Kweneng'), ('kaudwane_kweneng', 'Kaudwane Kweneng'), ('bere_ghanzi', 'Bere, Ghanzi District'), ('ghanzi', 'Ghanzi, Ghanzi District')], max_length=200, null=True, verbose_name='Village')),
                ('kgotla', models.CharField(blank=True, choices=[('malwelwe_kweneng', 'Malwelwe, Kweneng District'), ('komana_north_west', 'Komana, North West District'), ('nxaraga_ngamiland', 'Nxaraga, Ngamiland District'), ('werda_kgalagadi_south', 'Werda, Kgalagadi South District'), ('maun_ngamiland', 'Maun, Ngamiland District'), ('shakawe_north_west', 'Shakawe, North West District'), ('kang_kgalagadi_north', 'Kang, Kgalagadi North District'), ('bokspits_kgalagadi', 'Bokspits, Kgalagadi District'), ('tsetseng_kweneng', 'Tsetseng, Kweneng District'), ('gakhibana_kgalagadi_south', 'Gakhibana, Kgalagadi South District'), ('maubelo_kgalagadi_south', 'Maubelo, Kgalagadi South District'), ('kokotsha_kgalagadi_south', 'Kokotsha, Kgalagadi South District'), ('tsabong_kgalagadi_south', 'Tsabong, Kgalagadi South District'), ('etsha_6_ngamiland_west', 'Etsha 6, Ngamiland West District'), ('tsau_north_west', 'Tsau, North West District'), ('kuke_ghanzi', 'Kuke, Ghanzi'), ('inalegolo_kgalagadi_north', 'Inalegolo, Kgalagadi north'), ('lehututu_kgalagadi_north', 'Lehututu, Kgalagadi north'), ('hukuntsi_kgalagadi_north', 'Hukuntsi, Kgalagadi north'), ('tshane_kgalagadi_north', 'Tshane, Kgalagadi north'), ('diphuduhudu_kweneng', 'Diphuduhudu, Kweneng'), ('sorilatholo_kweneng', 'Sorilatholo, Kweneng'), ('tshwaane_kweneng', 'Tshwaane Kweneng'), ('kaudwane_kweneng', 'Kaudwane Kweneng'), ('bere_ghanzi', 'Bere, Ghanzi District'), ('ghanzi', 'Ghanzi, Ghanzi District')], max_length=200, null=True, verbose_name='Kgotla')),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plot Number')),
                ('household_type', models.CharField(blank=True, choices=[('male_headed', 'Male-headed'), ('female_headed', 'Female-headed'), ('elderly_male_headed', 'Elderly male-headed'), ('elderly_female_headed', 'Elderly female-headed'), ('child_headed', 'Child-headed')], max_length=200, null=True, verbose_name='Household type')),
                ('total_houshold_members', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Total number of persons who live in the household')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='Date of Interview')),
                ('enumerator_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Enumerator 's name")),
                ('enumerator_cell', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enumerator cell number')),
                ('begin_interview', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=10, null=True, verbose_name='Do you want to begin the interview?')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Household',
            },
        ),
        migrations.DeleteModel(
            name='FoodSecurityLivelihood',
        ),
    ]
