# Generated by Django 3.1.4 on 2021-07-05 19:33

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20210703_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='(suggest 40 characters max.)', max_length=250, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(db_index=True, help_text='This is the stored value, required', max_length=250, unique=True, verbose_name='Stored value')),
                ('display_index', models.IntegerField(db_index=True, default=0, help_text='Index to control display order if not alphabetical, not required', verbose_name='display index')),
                ('field_name', models.CharField(blank=True, editable=False, help_text='Not required', max_length=25, null=True)),
                ('version', models.CharField(default='1.0', editable=False, max_length=35)),
            ],
            options={
                'ordering': ['display_index', 'name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='household',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='household',
            name='subject_identifier_aka',
        ),
        migrations.RemoveField(
            model_name='household',
            name='subject_identifier_as_pk',
        ),
        migrations.AddField(
            model_name='household',
            name='household_identifier',
            field=models.CharField(default='11111111', editable=False, max_length=25, unique=True, verbose_name='Household Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='total_houshold_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total number of persons who live in the household'),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Number')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full name')),
                ('age_in_years', models.IntegerField(blank=True, help_text='(Years)', null=True, verbose_name='What is the participants age?')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('mother_in_law', 'Mother in law'), ('father_in_law', 'Father in law'), ('son_in_law', 'Son in law'), ('daughter_in_law', 'Daughter in law')], max_length=100, null=True, verbose_name='Relationship (e.g son, daughter, mother, father, son-in-law)')),
                ('education_level', models.CharField(blank=True, choices=[('plse', 'PLSE'), ('js', 'JC'), ('bgcse', 'BGCSE'), ('tertiary', 'Tertiary')], max_length=8, null=True, verbose_name='Education Level')),
                ('school_attendance', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Has been regularly attending school the past six months.')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=50, null=True, verbose_name='What is the marital status?')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.household')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
