# Generated by Django 3.1.4 on 2021-07-06 09:56

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20210705_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalProduction',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('area_owned', models.CharField(blank=True, help_text='Hectare', max_length=50, null=True, verbose_name='What is the total land area owned by household?')),
                ('area_cultivated', models.CharField(blank=True, help_text='Hectare', max_length=50, null=True, verbose_name='What is the total land area cultivated this season?')),
                ('area_rented', models.CharField(blank=True, help_text='Hectare', max_length=50, null=True, verbose_name='What is the total land area rented?')),
                ('method_watering', models.CharField(blank=True, choices=[('rain_fed', 'Rain-fed'), ('irrigated', 'Irrigated')], max_length=10, null=True, verbose_name='How do you water your crops')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgriculturalLivestockProduction',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('livestock_name', models.CharField(blank=True, choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('pigs', 'Pigs'), ('sheep', 'Sheep'), ('donkeys', 'Donkeys'), ('chickens', 'Chickens'), ('quinea_fowl', 'Guinea Fowls'), ('ducks', 'Ducks'), ('pigeons', 'Pigeons'), ('Other', 'Other specify')], max_length=100, null=True, verbose_name='Crop Name')),
                ('livestock_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='How many livestock do you currently own?')),
                ('increased_decreased', models.CharField(blank=True, choices=[('increased', 'Increased'), ('decreased', 'Decreased')], max_length=30, null=True, verbose_name='If increased or decreased')),
                ('reason', models.CharField(blank=True, max_length=40, null=True, verbose_name='State main reason for change')),
                ('agric_production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.agriculturalproduction')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgriculturalCropProduction',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('crop_name', models.CharField(blank=True, choices=[('mabele', 'Mabele'), ('groundnuts', 'GroundNuts'), ('sunflower', 'Sunflower'), ('maize_meal', 'Maize Meal(Mmidi)'), ('watermelon', 'Watermelon(Legapu)'), ('pumpkins', 'Pumpkins(Maphutse)'), ('sweet_reeds', 'Sweet Reeds(Ntshe)'), ('sugar_cane', 'Sugar Cane'), ('eggplant', 'EggPlant'), ('cabbage', 'Cabbage'), ('beans', 'Beans'), ('tomatoes', 'Tomatoes'), ('onions', 'Onions'), ('irish_potatoes', 'Irish Potatoes'), ('sweet_potatoes', 'Sweet Potatoes'), ('carrots', 'Carrots')], max_length=100, null=True, verbose_name='Crop Name')),
                ('hectares', models.CharField(blank=True, max_length=200, null=True, verbose_name='How many hectares')),
                ('expected_harvest', models.CharField(blank=True, max_length=200, null=True, verbose_name='How much do you expect to harvest?(KG)')),
                ('sell_crop', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=10, null=True, verbose_name='Do you intend to sell this crop')),
                ('sell_crop_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Why do you intend to sell this crop (main reason)?')),
                ('storage', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=10, null=True, verbose_name='Do you have storage for this crop?')),
                ('storage_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='What type of storage is this')),
                ('agric_production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.agriculturalproduction')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
