# Generated by Django 3.1.4 on 2021-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_agriculturalcropproduction_agriculturallivestockproduction_agriculturalproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturallivestockproduction',
            name='livestock_name_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other ,Specify'),
        ),
        migrations.AlterField(
            model_name='agriculturallivestockproduction',
            name='livestock_name',
            field=models.CharField(blank=True, choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('pigs', 'Pigs'), ('sheep', 'Sheep'), ('donkeys', 'Donkeys'), ('chickens', 'Chickens'), ('quinea_fowl', 'Guinea Fowls'), ('ducks', 'Ducks'), ('pigeons', 'Pigeons'), ('Other', 'Other specify')], max_length=100, null=True, verbose_name='Livestock Name'),
        ),
    ]
